BEGIN {
    #  $1 Book name
    #  $2 Book abbreviation
    #  $3 Book number
    #  $4 Chapter number
    #  $5 Verse number
    #  $6 Verse
    FS = "\t"
    print "/* This file is automatically generated. DO NOT EDIT. */"
    print "#include <stddef.h>"
    print "#include \"data.h\""
    print ""
    print "kjv_verse kjv_verses[] = {"
}

{
    printf("    {\"%s\", \"%s\", %d, %d, %d, \"%s\"},\n", $1, $2, $3, $4, $5, $6)
}

END {
    print "};"
    print ""
    printf("int kjv_verses_length = %d;\n", NR)
}
